[Unit]
After=dzap-backend.service systemd-sysusers.service systemd-tmpfiles-setup.service
Wants=dzap-backend.service

[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --noreset --noclear --autologin dzap - ${TERM}
