"use client";

import React, { useState } from "react";
import {
	FileCheck,
	ShieldCheck,
	Download,
	Copy,
	Check,
	X,
	FileText,
	Printer,
	ExternalLink,
	Hash,
	Calendar,
	User,
	Cpu,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { ChainOfCustodyReport } from "@/lib/types";

interface ChainOfCustodyModalProps {
	report: ChainOfCustodyReport | null;
	isOpen: boolean;
	onClose: () => void;
}

export function ChainOfCustodyModal({ report, isOpen, onClose }: ChainOfCustodyModalProps) {
	const [copied, setCopied] = useState(false);

	if (!isOpen || !report) return null;

	const handleCopyJson = () => {
		navigator.clipboard.writeText(JSON.stringify(report, null, 2));
		setCopied(true);
		setTimeout(() => setCopied(false), 2000);
	};

	const handleDownloadJson = () => {
		const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
		const url = URL.createObjectURL(blob);
		const a = document.createElement("a");
		a.href = url;
		a.download = `${report.report_id}.json`;
		a.click();
		URL.revokeObjectURL(url);
	};

	const handlePrint = () => {
		window.print();
	};

	return (
		<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in duration-200">
			<div className="bg-card border border-border rounded-2xl shadow-2xl w-full max-w-4xl max-h-[92vh] overflow-hidden flex flex-col animate-in zoom-in-95 duration-200">
				{/* Modal Top Header */}
				<div className="px-6 py-4 border-b border-border/70 flex items-center justify-between bg-muted/20">
					<div className="flex items-center space-x-3">
						<div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
							<ShieldCheck className="h-5 w-5" />
						</div>
						<div>
							<h3 className="text-base font-bold text-foreground flex items-center gap-2">
								<span>Forensic Chain of Custody Certificate</span>
								<Badge className="bg-emerald-600 text-white text-xs font-mono">
									DIGITALLY SEALED
								</Badge>
							</h3>
							<p className="text-xs text-muted-foreground font-mono">
								Report ID: {report.report_id} | Standards: ISO/IEC 27037 & NIST SP 800-86
							</p>
						</div>
					</div>
					<button
						type="button"
						onClick={onClose}
						className="p-1.5 rounded-lg hover:bg-accent text-muted-foreground hover:text-foreground transition-colors"
					>
						<X className="h-5 w-5" />
					</button>
				</div>

				{/* Modal Scrollable Content */}
				<div className="p-6 overflow-y-auto flex flex-col gap-6 text-foreground font-sans">
					{/* Official Header Banner */}
					<div className="p-4 rounded-xl border border-emerald-500/30 bg-emerald-500/5 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
						<div>
							<h4 className="font-bold text-sm text-foreground">{report.title}</h4>
							<p className="text-xs text-muted-foreground mt-0.5">
								Generated by {report.tool_name} v{report.tool_version}
							</p>
						</div>
						<div className="text-right font-mono text-xs text-muted-foreground">
							<div>Case: <strong className="text-foreground">{report.case_id}</strong></div>
							<div>Date: <strong className="text-foreground">{new Date(report.generated_at).toLocaleString()}</strong></div>
						</div>
					</div>

					{/* Case & Custody Metadata Grid */}
					<div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
						<div className="p-3 rounded-lg border border-border/60 bg-background/50">
							<span className="text-muted-foreground block text-[11px]">Evidence Target</span>
							<span className="font-mono font-bold text-foreground text-sm">{report.target_device}</span>
						</div>
						<div className="p-3 rounded-lg border border-border/60 bg-background/50">
							<span className="text-muted-foreground block text-[11px]">Sectors Analyzed</span>
							<span className="font-mono font-bold text-foreground text-sm">{report.total_sectors_scanned.toLocaleString()}</span>
						</div>
						<div className="p-3 rounded-lg border border-border/60 bg-background/50">
							<span className="text-muted-foreground block text-[11px]">Carved Artifacts</span>
							<span className="font-mono font-bold text-emerald-600 dark:text-emerald-400 text-sm">
								{report.total_artifacts_carved} ({report.high_confidence_count} high conf)
							</span>
						</div>
						<div className="p-3 rounded-lg border border-border/60 bg-background/50">
							<span className="text-muted-foreground block text-[11px]">Reassembled Gaps</span>
							<span className="font-mono font-bold text-foreground text-sm">{report.fragmented_count}</span>
						</div>
					</div>

					{/* Digital Integrity Seal */}
					<div className="p-4 rounded-xl border border-border/70 bg-muted/20 flex flex-col gap-2">
						<div className="flex items-center justify-between text-xs">
							<span className="font-bold text-foreground flex items-center gap-1.5">
								<Hash className="h-4 w-4 text-emerald-500" />
								Report Cryptographic Integrity Digest (SHA-256):
							</span>
							<Badge variant="outline" className="text-[10px] font-mono">
								{report.digital_signature_algorithm}
							</Badge>
						</div>
						<div className="p-2 rounded bg-background border border-border/50 font-mono text-[11px] select-all break-all text-emerald-700 dark:text-emerald-400">
							{report.integrity_digest_sha256}
						</div>
						<div className="text-[11px] text-muted-foreground font-mono">
							Verification Seal: <span className="text-foreground">{report.digital_signature_seal}</span>
						</div>
					</div>

					{/* Academic & Forensic Standards Referenced */}
					<div className="flex flex-col gap-1 text-xs">
						<span className="font-bold text-muted-foreground text-[11px] uppercase tracking-wider">
							Academic & Industry Benchmarks:
						</span>
						<ul className="list-disc list-inside text-xs text-muted-foreground space-y-0.5 font-mono">
							{report.standard_references.map((std, idx) => (
								<li key={idx} className="truncate">{std}</li>
							))}
						</ul>
					</div>

					{/* Artifact Ledger Table */}
					<div className="flex flex-col gap-2">
						<span className="font-bold text-xs text-foreground">
							Carved Evidence Ledger ({report.artifacts.length} entries):
						</span>
						<div className="rounded-xl border border-border/70 overflow-x-auto max-h-56 bg-background/50 text-xs font-mono">
							<table className="w-full text-left">
								<thead className="bg-muted/40 border-b border-border/60 text-muted-foreground sticky top-0">
									<tr>
										<th className="py-2 px-3">ID</th>
										<th className="py-2 px-3">Filename</th>
										<th className="py-2 px-3">Sector Range</th>
										<th className="py-2 px-3">Confidence</th>
										<th className="py-2 px-3">SHA-256</th>
									</tr>
								</thead>
								<tbody className="divide-y divide-border/40">
									{report.artifacts.map((a) => (
										<tr key={a.id} className="hover:bg-accent/30">
											<td className="py-1.5 px-3 text-emerald-600 dark:text-emerald-400 font-semibold">{a.id}</td>
											<td className="py-1.5 px-3 font-semibold">{a.filename}</td>
											<td className="py-1.5 px-3">#{a.start_sector}..{a.end_sector}</td>
											<td className="py-1.5 px-3">{Math.round(a.confidence_score * 100)}%</td>
											<td className="py-1.5 px-3 text-muted-foreground truncate max-w-[150px]" title={a.sha256}>
												{a.sha256.slice(0, 16)}...
											</td>
										</tr>
									))}
								</tbody>
							</table>
						</div>
					</div>
				</div>

				{/* Modal Action Footer */}
				<div className="px-6 py-4 border-t border-border/70 flex items-center justify-between bg-muted/20">
					<Button variant="outline" size="sm" onClick={handlePrint} className="text-xs flex items-center gap-1.5">
						<Printer className="h-3.5 w-3.5" />
						Print Certificate
					</Button>
					<div className="flex items-center space-x-2">
						<Button variant="outline" size="sm" onClick={handleCopyJson} className="text-xs flex items-center gap-1.5">
							{copied ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
							<span>{copied ? "Copied JSON" : "Copy JSON"}</span>
						</Button>
						<Button
							size="sm"
							onClick={handleDownloadJson}
							className="bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold flex items-center gap-1.5"
						>
							<Download className="h-3.5 w-3.5" />
							Download JSON Report
						</Button>
					</div>
				</div>
			</div>
		</div>
	);
}
